import Head from "next/head";
import { useState, useEffect } from "react";
import { Container, Main, Title } from "../components/styledComponents/Main";

export default function Home() {
  return (
    <Container main>
      <Head>
        <title>Karafs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>Karafs</Title>
      </Main>
    </Container>
  );
}
